### ISSUE TITLE
NDT Rviz plugin can not display NDT map using DistributionsPublisher??

### ISSUE THREAD

**Issue by will1991** [cogsys-tuebingen/cslibs_ndt#4]
The map can be visualized using PointcloudPulisher,This is  my launch file.
[velodyne.txt](https://github.com/cogsys-tuebingen/cslibs_ndt/files/3504884/velodyne.txt)

I am using ubuntu 18.04 and ros melodic.

**Comment by c-schulz** [comment]
Hello @will1991 

we experienced difficulties with other self-compiled RVIZ plugins as well. Is it possible, that there is a 'devel' folder inside your 'build' folder and that you need to source '<path>/build/devel/setup.sh' before starting RVIZ? I remember that this worked for a different RVIZ plugin.

However, I would in general recommend you to use the PointcloudPublisher, since it is faster (for the DistributionsPublisher, eigenvectors etc. are calculated), and the RVIZ plugin for Distributions is also rather slow if there are loads of distributions to be rendered (I had fps drops to <1 fps with Velodyne VLP-16 outdoor data). The DistributionsPublisher was intended mainly for debugging and needs to be improved massively for online usage.

If you use the PointcloudPublisher, try setting the RVIZ parameters to render boxes of about half the resolution or 1/4 of the resolution, and color by height, then you get a reasonable visualization similar to something like OctoMap.

And please note, that the resolution you specify in your launch file will be 2x the effective resolution of your grid, e.g. for 0.5m effective resolution you need to specify 1m in your launch file. Further, the 3D ONDT version is currently undergoing a rework, since the map update is too slow; I hope there will be an update soon (hopefully in the next few weeks).

Best wishes
